spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: off
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8282
  servlet:
    context-path: /api/deposits