spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: off
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: true
server:
  port: 8282
  servlet:
    context-path: /api/deposits