# thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=true

# database conn
spring.datasource.url=jdbc:postgresql://10.0.90.141:15432/depositos_db
spring.datasource.username=postgres
spring.datasource.password=I62oTi8AYmc4Ii!
spring.datasource.driver-class-name=org.postgresql.Driver

cavapy.ldap.url=ldap://10.0.1.223:389
cavapy.ldap.base=dc=cavapy,dc=com,dc=py
cavapy.ldap.dnPatterns=cn=Manager,dc=cavapy,dc=com,dc=py
cavapy.ldap.password=CavDep#381py

cavapy.core.bank.account.url=http://10.0.1.112:8086/api/core/v1/banks/accounts/info
cavapy.core.user.profile.url=http://10.0.1.112:8086/api/core/v1/users/find/user/?/profile