# thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true

# database conn
spring.datasource.url=${ENV_URL}
spring.datasource.username=${ENV_USERNAME}
spring.datasource.password=${ENV_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

cavapy.ldap.url=${ENV_LDAP_URL}
cavapy.ldap.base=dc=cavapy,dc=com,dc=py
cavapy.ldap.dnPatterns=cn=Manager,dc=cavapy,dc=com,dc=py
cavapy.ldap.password=${ENV_LDAP_PASSWORD}

# core ms
cavapy.core.bank.account.url=http://10.0.12.113:8086/api/core/v1/banks/accounts/info
cavapy.core.user.profile.url=http://10.0.12.113:8086/api/core/v1/users/find/user/?/profile