package cavapy.api.py.continental.enums;

public enum SystemProfileType {

    AUDITORIA_SUPERVISOR(1087, "CAVAPY - AUDITORIA SUPERVISOR"),

    OPERACIONES_SUPERVISOR(1091, "CAVAPY - OPERACIONES - SUPERVISOR"),

    CUSTODIA_OPERADOR(1093, "CAVAPY - CUSTODIA OPERADOR"),

    OPERACIONES_OPERADOR(1090, "CAVAPY - OPERACIONES - OPERADOR"),

    OPERADOR_NOCTURNO(1141, "CAVAPY - OPERADOR NOCTURNO"),

    ADMINISTRACION_Y_FINANZAS_CONSULTA(234, "CAVAPY - ADMINISTRACION Y FINANZAS CONSULTA"),

    OPERACIONES_CIERRE(273, "CAVAPY - OPERACIONES CIERRE "),

    ADMINISTRACION_Y_FINANZAS_SUPERVISOR(232, "CAVAPY - ADMINISTRACION Y FINANZAS SUPERVISOR"),

    OPERACIONES_GERENCIA_GENERAL(493, "CAVAPY - OPERACIONES GERENCIA GENERAL"),

    LIQUIDACIONES_Y_EMISIONES_OPERADOR(774, "CAVAPY LIQUIDACIONES Y EMISIONES OPERADOR"),

    ADMINISTRACION_Y_FINANZAS_OPERADOR(233, "CAVAPY - ADMINISTRACION Y FINANZAS OPERADOR"),

    CUSTODIA_GERENCIA(1094, "CAVAPY - CUSTODIA GERENCIA"),

    ADMINISTRADOR_DEL_SISTEMA(324, "CAVAPY - ADMINISTRADOR DEL SISTEMA"),

    CUSTODIA_SUPERVISOR(1095, "CAVAPY - CUSTODIA SUPERVISOR"),

    OPERACIONES_GERENCIA(253, "CAVAPY - OPERACIONES - GERENCIA"),

    LEGAL_CONSULTA(1086, "CAVAPY - LEGAL CONSULTA"),

    ADMINISTRACION_Y_FINANZAS_TESORERIA(69611, "CAVAPY ADMINISTRACION Y FINANZAS TESORERIA"),

    TI_CONSULTA(1089, "CAVAPY - TI CONSULTA");

    private final Integer code;

    private final String value;

    SystemProfileType(Integer code, String value) {
        this.code = code;
        this.value = value;
    }

    public Integer getCode() {
        return code;
    }

    public String getValue() {
        return value;
    }
}
